// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Week2Deel1;

namespace Week2Deel1.Migrations
{
    [DbContext(typeof(HuisenContext))]
    [Migration("20171120174813_MySecond")]
    partial class MySecond
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Week2Deel1.Huis", b =>
                {
                    b.Property<int>("HuisId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AantalKamers");

                    b.Property<int>("Bouwjaar");

                    b.Property<string>("Plaats");

                    b.HasKey("HuisId");

                    b.ToTable("Huisen");
                });
#pragma warning restore 612, 618
        }
    }
}
